### ISSUE TITLE
Service squid3 is unknown

### ISSUE THREAD

**Issue by snm247** [YunoHost-Apps/squid3_ynh#6]
### Describe the bug

YunoHost diagnosis shows the following warning:

> Service squid3 is unknown :(
> 
>    You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with yunohost service restart squid3 and yunohost service log squid3).

### Context

- Hardware: Old laptop or computer*
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using: 1.0~ynh2

### Steps to reproduce

* Running YunoHost diagnosis in the webadmin shows the warning above.
* `systemctl status` shows that there is a `squid.service` (which is active and running) but no `squid3.service`.
* `yunohost service status` has the following result for `squid3` (no result for `squid`):

```
squid3: 
  configuration: unknown
  description: Error: failed to get information for this service, it doesn't exists for systemd
  last_state_change: unknown
  start_on_boot: unknown
  status: unknown
```

It seems YunoHost diagnosis checks the wrong service name.

### Expected behavior

YunoHost diagnosis should check the correct service name.
